"""add description field  to interview table

Revision ID: 0ffcc0d68431
Revises: 629d78184244
Create Date: 2021-12-26 15:06:07.250541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ffcc0d68431'
down_revision = '629d78184244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('short_description', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview', 'short_description')
    # ### end Alembic commands ###
