"""add timestamp field  to interview grade and question table

Revision ID: 2a485a76386e
Revises: 0ffcc0d68431
Create Date: 2021-12-26 15:08:07.168404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a485a76386e'
down_revision = '0ffcc0d68431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_grade_timestamp'), 'grade', ['timestamp'], unique=False)
    op.add_column('interview', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_interview_timestamp'), 'interview', ['timestamp'], unique=False)
    op.add_column('question', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_question_timestamp'), 'question', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_timestamp'), table_name='question')
    op.drop_column('question', 'timestamp')
    op.drop_index(op.f('ix_interview_timestamp'), table_name='interview')
    op.drop_column('interview', 'timestamp')
    op.drop_index(op.f('ix_grade_timestamp'), table_name='grade')
    op.drop_column('grade', 'timestamp')
    # ### end Alembic commands ###
