"""add time fields to intercview

Revision ID: 960ea5c7cf84
Revises: 2a485a76386e
Create Date: 2021-12-26 23:44:52.317244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960ea5c7cf84'
down_revision = '2a485a76386e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('link', sa.String(), nullable=True))
    op.add_column('interview', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('interview', sa.Column('time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview', 'time')
    op.drop_column('interview', 'date')
    op.drop_column('interview', 'link')
    # ### end Alembic commands ###
