"""add cascade delete to grade table

Revision ID: a89de461ccb4
Revises: 960ea5c7cf84
Create Date: 2021-12-28 17:13:57.567880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89de461ccb4'
down_revision = '960ea5c7cf84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('grade_interview_id_fkey', 'grade', type_='foreignkey')
    op.drop_constraint('grade_interviewer_id_fkey', 'grade', type_='foreignkey')
    op.drop_constraint('grade_question_id_fkey', 'grade', type_='foreignkey')
    op.create_foreign_key(None, 'grade', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'grade', 'interview', ['interview_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'grade', 'user', ['interviewer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grade', type_='foreignkey')
    op.drop_constraint(None, 'grade', type_='foreignkey')
    op.drop_constraint(None, 'grade', type_='foreignkey')
    op.create_foreign_key('grade_question_id_fkey', 'grade', 'question', ['question_id'], ['id'])
    op.create_foreign_key('grade_interviewer_id_fkey', 'grade', 'user', ['interviewer_id'], ['id'])
    op.create_foreign_key('grade_interview_id_fkey', 'grade', 'interview', ['interview_id'], ['id'])
    # ### end Alembic commands ###
