"""empty message

Revision ID: c22c587f1775
Revises: a89de461ccb4
Create Date: 2021-12-29 00:05:28.399334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22c587f1775'
down_revision = 'a89de461ccb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('grade_interviewer_id_fkey', 'grade', type_='foreignkey')
    op.drop_constraint('grade_question_id_fkey', 'grade', type_='foreignkey')
    op.drop_constraint('grade_interview_id_fkey', 'grade', type_='foreignkey')
    op.create_foreign_key(None, 'grade', 'user', ['interviewer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'grade', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'grade', 'interview', ['interview_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grade', type_='foreignkey')
    op.drop_constraint(None, 'grade', type_='foreignkey')
    op.drop_constraint(None, 'grade', type_='foreignkey')
    op.create_foreign_key('grade_interview_id_fkey', 'grade', 'interview', ['interview_id'], ['id'])
    op.create_foreign_key('grade_question_id_fkey', 'grade', 'question', ['question_id'], ['id'])
    op.create_foreign_key('grade_interviewer_id_fkey', 'grade', 'user', ['interviewer_id'], ['id'])
    # ### end Alembic commands ###
